version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    ulimits:
      nofile: # Fix memory leak issue on some systems when LimitCORE=infinity (containerd)
        soft: 1048576
        hard: 1048576
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "manytoone"
     
    ports:
      - "3306:3306"
    networks:
      - bridge

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - bridge

networks: 
  bridge:
    driver: bridge
    
